### ISSUE TITLE
isComplianceCheck field in Azure Policy Log Activity

### ISSUE THREAD

**Issue by thuansoldier** [Azure/azure-policy#145]
Hi @pilor 

What does **isComplianceCheck** mean in Azure Policy activity log? It's Boolean field.

`"isComplianceCheck": "False"`

**Comment by pilor** [comment]
if "isComplianceCheck": "True" that means the policy evaluation was caused by the intermittent compliance scans that we perform to ensure that the compliance state we expose in the Azure Portal (and via APIs) is up to date.

"isComplianceCheck": "False" indicates the evaluation was caused by a PUT or PATCH request against the resource that was evaluated.

**Comment by thuansoldier** [comment]
It could not be any quicker response. Thank you very much.
