### ISSUE TITLE
Feature request: "Microsoft.Authorization/roleAssignments/scope"

### ISSUE THREAD

**Issue by byron70** [Azure/azure-policy#176]
**Scenario**

Enforce role assignments restrictions, but allow a particular resource type to be by-passed when enforcing the restriction.  The current "Exclusions" for role assignments are either too broad or granular (entire resource groups or specific resources). Would like to allow a role assignment for any give resource namespace or type, something like the following examples.

`byPassScope = 'Micrsoft.Web/'`

or similarly,

`byPassScope = 'Micrsoft.Web/sites'`

**Definition**

```
{
  "if": {
    "allOf": [
      {
        "equals": "Microsoft.Authorization/roleAssignments",
        "field": "type"
      },
      {
        "not": {
          "field": "Microsoft.Authorization/roleAssignments/roleDefinitionId",
          "in": "[parameters('roleDefinitionIds')]"
        }
      },
      {
        "not": {
          "field": "Microsoft.Authorization/roleAssignments/scope",
          "contains": "[parameters('byPassScope')]"
        }
      },
    ]
  },
  "then": {
    "effect": "deny"
  }
}
```

**Comment by bebattis** [comment]
Wondering if there are any updates regarding this alias/feature. I am also looking to block RBAC assignments at the individual resource level.

**Comment by hrboyceiii** [comment]
Agreed, any updates on this request?

**Comment by mentat9** [comment]
The full set of aliases for Microsoft.Authorization has been published. However, the alias you requested is only present in GET payloads. We only publish aliases for fields that are present in both GET and PUT methods, because policy requires managing both operations. The scope is specified in the URI on PUT, so it's not possible to manage it via policy. Sorry we can't support your scenario.

**Comment by hrboyceiii** [comment]
Bummer. That's incredibly misleading. The arm template reference (https://docs.microsoft.com/en-us/azure/templates/microsoft.authorization/2017-09-01/roleassignments) includes scope as a property that is settable -- which makes one think this is part of the payload available to policy for evaluation.

I understand now that the result is a set of api calls and not necessarily a 1:1 between arm template schemas and apis...

Is there an appropriate channel for changing this for better alignment/consistency?

**Comment by mentat9** [comment]
I'll pass this thread along to the resource provider team. Also, you might want to take a look at Audit/DeployIfNotExist policies as well. I don't have a specific pattern in mind, but maybe you can figure out a way to do what you want by adding checks in the existence condition or the deployment template.

**Comment by hrboyceiii** [comment]
Thanks @mentat9. My thought was a deny policy that would block specifically roles on based upon scope to only allow service principals and not users or groups.  That may be an oddball use case but basically preventing potential manual changes by individuals and not a CI/CD process.

I sincerely appreciate you closing the loop here. Thank you again

**Comment by andaryjo** [comment]
> We only publish aliases for fields that are present in both GET and PUT methods, because policy requires managing both operations. The scope is specified in the URI on PUT, so it's not possible to manage it via policy. Sorry we can't support your scenario.

@mentat9 That does not seem to be (entirely) correct (anymore)? In older API versions (for example 2020-04-01-preview, which the Azure Portal still uses), you can supply a scope using the `scope` property. The Azure Portal does exactly that, additionally to putting it in the request URI.

In that case the alias `Microsoft.Authorization/roleAssignments/scope` would actually represent the scope provided by the Azure Portal.

You can even be sure that when the scope gets provided this way, it has to be the correct one (which actually surprised me), because the API will throw an error if the scope provided as `scope` property does not match the scope in the URI.

![SCR-20240525-lcqi](https://github.com/Azure/azure-policy/assets/66257646/84059892-88d5-49d5-9d7f-b3fab3ae8059)

This also works with the most recent API version "2022-04-01", where the `scope` property isn't even part of the API request payload anymore according to the specs.

With that you could design a policy that denies all role assignments if `Microsoft.Authorization/roleAssignments/scope` is null and then allows / denies specific scopes. I wouldn't recommend it since it breaks all Azure clients that don't supply a scope as payload property (for example the azurerm Terraform provider), but it would (for the moment) work for the Azure Portal.

**Comment by andaryjo** [comment]
Some Azure clients (for example Terraform) also put the role assignment scope in front of the role assignment ID. You could design a policy that checks for that, even though it would not work for all clients that don't do that, since it is not required for built-in roles.
