### ISSUE TITLE
Platform Image Policy has a bug

### ISSUE THREAD

**Issue by slavizh** [Azure/azure-policy#180]
As described in my blog post:
https://cloudadministrator.net/2018/08/27/platform-image-azure-policy-definition-example/

the policy is not working correctly. I think latest should allow latest images without specifying specific version. Also latest should move automatically when newer version is published. That way you can have policy that do not have to update all the time and your engineers can use the latest version.

**Comment by camillemarie** [comment]
Good catch. The VM resource passes the template "preflight" validation because the imageReference is using "version":"latest", but it gets denied at the disk level because the Compute RP fills in the image version with the actual version string when it is creating the nested disk resource. Will remove the version restriction and parameterize the policy.

------------
Unfortunately, inferring the latest version is currently non-trivial, as the policy evaluation engine lives in ARM and operates on the JSON representation of the resource being created/updated. It is not aware of the image versions or the meaning of "latest", which are maintained by the Microsoft.Compute resource provider. We are designing a solution for RP-specific logic in Policy, but it will take some time to get it right.

For now, I would add an "Audit" policy for the versions. As you mentioned, it would need to be maintained regularly, but at least it wouldn't block anyone.

**Comment by pilor** [comment]
Removing version altogether from that sample policy as most use cases I've seen for image restrictions are attempting to restrict OS type/version but don't care about the specific image version.  

Pulling in extra metadata from outside sources during policy evaluation isn't planned to be supported (it would be useful but it introduces a lot of problems).
