### ISSUE TITLE
Alias request: "Microsoft.Compute/virtualMachines/id"

### ISSUE THREAD

**Issue by vijaynar** [Azure/azure-policy#189]
Need to pass the non compliant VM id as input the API for EnableDR scenario.

**Comment by pilor** [comment]
ID isn't a field that policy is exposing at the moment.  If it was added it would be as a built-in field instead of a type-specific alias.  The timeline for that is going to be longer than what you want to wait for.

It should be possible for you to re-form the ID using the [concat()] [subscription()] and [resourceGroup()] functions.  We've done that in other similar scenarios.  Does that sound like something you can take advantage of?

**Comment by vijaynar** [comment]
I tried building VmId using this strategy :
 [concat('/subscriptions/', subscription().subscriptionId, '/resourcegroups/', resourceGroup().name, '/providers/Microsoft.Compute/virtualMachines/', field('name'))]
 
But it gave resourceGroup where template was executing not failed resource (VM) RG. 
"code": "150015",
 "message": "Azure Virtual machine with Id (/subscriptions/d90d145a-4cdd-45a3-b2c4-971d69775278/resourcegroups/policy-based-enabledr-try-rec/providers/microsoft.compute/virtualmachines/policy-3) couldn't be found."

Seems like this is not working. Can you please approve this alias till Id comes as build-in policy

**Comment by pilor** [comment]
This was resolved offline.  The VM ID should be built in the input "parameters" section of the template so that it uses policy-scoped functions and not deployment-scoped functions.

Example:

```
"parameters": {
            "vmName": {
              "value": "[field('name')]"
            },
            "apiVersion": {
              "value": "2018-01-10"
            },
…

            "vmId": {
              "value": [concat('/subscriptions/', subscription().subscriptionId, '/resourcegroups/', resourceGroup().name, '/providers/Microsoft.Compute/virtualMachines/', field('name'))]"
            },
…
          }
```

**Comment by paolosalvatori** [comment]
Did you create a built-in field for the resource id in the meantime?
