### ISSUE TITLE
Azure Policy compliance latency

### ISSUE THREAD

**Issue by JamesDuggan** [Azure/azure-policy#212]
The latency around the time a policy is assigned and executed for compliance is woefully unpredictable and   a bad experience for several reasons, not least feedback time when developing and testing.

The only work around is to create a version as deny effect and then test when altering the resource. That works well if and only if all rules are implemented as if <condition> and then only accepting effect as audit or deny.

Providing some control such as Execute Now for assigned policies would go a long way, as would decreasing the latency and increasing execution predictability.

**Comment by LizMS** [comment]
Hi James, thanks for the feedback.
We recently released a new change in Azure Policy, where a new assignment will return iterative results as Compliance scan is in progress rather than having to wait until the full scan is finished. Additionally, the compliance state will say 'Not started' if the scan hasn't started. From my experience, it takes ~10 minutes for the scan to start. From that point on, you will see the list of resources that have been evaluated (we filter to non-compliant resources by default, but you can change the filter to see compliant resources as well) and 'last evaluated' timestamp.

For updating an existing assignment, the iterative results still apply. When you 'save' the assignment, it triggers a full scan on our evaluation engine. So you should start to see resources with updated 'last evaluated' timestamp as they get re-evaluated.

**Comment by JamesDuggan** [comment]
Hi Liz,

amazing response time by the way. What you describe is not what I am seeing. Though I have access to may subscriptions with many resources, the polices are test ones and assigned to a subscription with less than 10 resources and are targeted at Azure SQL Database. They were when I last looked in "not started" state for about 6 hours. 

I have also observed resources remaining in non compliant state for for over 24hrs after the resource was deleted.

**Comment by LizMS** [comment]
Hi James,

Could you confirm that you have SQL databases in the assignment scope?
It'll say 'not started' if there aren't any applicable resources (e.g. SQL databases).

Otherwise, please shoot me an email at elkim@microsoft.com with your subscription ID and policy definition. We will investigate it.

Resource deletion clean-up occurs within 20 minutes **IF** there was a corresponding activity log event for the deletion.
Otherwise, it will be on the next full-scan which occurs every 24 hours (24 hours + the duration of the scan = maximum wait time for the clean-up).

**Comment by JamesDuggan** [comment]
Hi Liz,

I've forwarded details via email. Looking forward to your response.

James

**Comment by pilor** [comment]
Assuming this is being taken care of over e-mail given the last two responses.  Re-open if you need additional help.

**Comment by dufain** [comment]
@LizMS @JamesDuggan 
I'm experiencing the EXACT same problem. Scan time seems completely random. Policies can be assigned and some work fine while others show "Not Started" for over 24 hours. Would appreciate if you could post the conclusion of you work together, to hopefully assist myself/others in troubleshooting similar issues.

**Comment by pinaki1234** [comment]
Hi there I am seeing the same latency issue now almost 7 months from the last post. I see the compliance state as "Not Started" even after 1 hour of saving the initiative. Has anything been updated on Azure's end (at all)?

**Comment by mentat9** [comment]
Sorry for the latency and any difficulty it caused you. This was likely due to some degradation in storage and related basic services around the time you reported this. If it continues, please open a support ticket.

**Comment by dpr477** [comment]
@JamesDuggan Was this ever resolved and was the resolution something that others may benefit from?
