### ISSUE TITLE
Alias request: Microsoft.Insights/Components/ProactiveDetectionConfigs/sendEmailsToSubscriptionOwners

### ISSUE THREAD

**Issue by wagsousa** [Azure/azure-policy#213]
**Scenario**
Whenever a new Application Insights is created need to define a policy that will disable sendEmailsToSubscriptionOwners by setting it to false. As we don't want notifications to be sent to the Subscriptions owners.

**Definition**

```
{
   "if":{
      "allOf":[
         {
            "field":"type",
            "equals":"Microsoft.Insights/Components/ProactiveDetectionConfigs"
         },
         {
            "field":"Microsoft.Insights/Components/ProactiveDetectionConfigs/sendEmailsToSubscriptionOwners",
            "equals":"true"
         }
      ]
   },
   "then":{
      "effect":"deny"
   }
}
```

**Comment by mentat9** [comment]
The full set of aliases for Microsoft.Insights has been published. Unfortunately, this alias was not published because the current version of the proactive detection API has not been published by the app insights team. Until they publish the swagger for that API, we won't be able to generate aliases and thus won't be able to manage this field via policy. We are engaging them to get these steps done, but it will likely be a while before we can add this alias.

**Comment by mentat9** [comment]
The app insights team has updated their swagger files, and I've published the new aliases, so the requested aliases (and others) are now available for use in your policies.
