### ISSUE TITLE
limited deny capability results in leaky policies

### ISSUE THREAD

**Issue by JamesDuggan** [Azure/azure-policy#227]
The deny and audit effects should be extended to enable testing of related resources as part of the if <condition> statement. For example, 

"if" : {
        "allOf": [
          {
            "field": "type",
            "equals": "Microsoft.Sql/servers/databases"
          },
         "exists" | "notExists" : {
            "type": "Microsoft.Sql/servers/databases/transparentDataEncryption",
            "name": "current",
            "existenceCondition": {
              ...
            }
          }
        ]
},
"then" : {
  "effect" : "deny"
}

Without this, the effects are leaky and enforcing compliance is harder than it should be

**Comment by pilor** [comment]
You can audit in these scenario using the AuditIfNotExists effect:
https://docs.microsoft.com/en-us/azure/governance/policy/concepts/effects#auditifnotexists

However, "deny" is not supported when pulling in related resources due to technical limitations.  We don't plan to change that in the near future.

**Comment by JamesDuggan** [comment]
The purpose of a policy implementing the deny effect should be to prevent a resource that is not compliant from being created. 
As implemented the deny effect is leaky as it allows not compliant resources to be created. Another way of putting this is the deny effect is broken by design since its evaluation capability is limited. 
To suggest using the AuditIfNotExists is missing the point and offers neither additional benefit nor appropriate work around.
For these reasons this issue should be reopened since the deny effect is broken.

**Comment by pilor** [comment]
"Deny" is not supported in scenarios that involve related resources.  This is by design.

To enforce that every SQL DB has transparent data encryption enabled you can use a "deployIfNotExists" policy in combination with an explicit "deny".  There is a built-in deployIfNotExists policy that deploys TDE if it is not enabled on any new SQL DBs named "Deploy SQL DB transparent data encryption".  You could combine that policy with a policy that prevents a user from disabling TDE once it is enabled (something like this: https://github.com/Azure/azure-policy/tree/master/samples/SQL/deny-sql-db-tde-disabled).

**Comment by JamesDuggan** [comment]
I think it best not to focus on the contrived example and instead on the meaning of deny. It should prevent resources from existing that are not compliant. It does not achieve this. I get that given the variety of deployment mechanisms, from portal to powershell and everything in between this is hard, however, the word has a specific meaning and with it a required implementation. 

I assert that to be a functional effect if should be able to support related resources and absent of this it is broken by design and therefore a bug.

For reference that sample is also broken as it does not exclude the master database and the resultant compliance reports a noisy.
