### ISSUE TITLE
DeployIfNotExists audits existing resources, but not after remediation

### ISSUE THREAD

**Issue by trolleyboy** [Azure/azure-policy#255]
I've created a Policy using DeployIfNotExists to Deploy HttpsOnly for App Services websites.  
For existing sites, the policy is evaluated and reports the appropriate services that don't have HttpsOnly set to True as Non-compliant.  Remediation works well too.  
However after remediating the setting via a Policy Remediation Task, if someone manually sets the HttpsOnly setting back to False, the Policy is again evaluated against the resource but incorrectly reports a Compliant status.  I'm unable to remediate as the resources don't appear in the list of resources to remediate.  

Policy JSON is in the attached txt file. 
[DeployIfNotExists WebApps HttpsOnly.txt](https://github.com/Azure/azure-policy/files/2578899/DeployIfNotExists.WebApps.HttpsOnly.txt)

**Comment by pilor** [comment]
The policy is going to look at all of the Microsoft.Web/sites in the resource group and only be non-compliant if they are ALL httpsOnly=false.

Set the "name" property in the deployIfNotExists effect details to "[field('name')]" to have it only look at the site that was being evaluated in the IF condition and you should get the behavior you desire.

https://docs.microsoft.com/en-us/azure/governance/policy/concepts/effects#deployifnotexists

**Comment by trolleyboy** [comment]
Great tip @pilor , thanks!  
It's helped report the correct compliance status.  However I now find that the Deploy occurs on existing resources.  HttpsOnly is set back to True for applicable Apps without someone running a Remediation task.  Azure Docs indicates that this "auto-remediation" should not happen with existing resources, but I've also read in https://github.com/Azure/azure-policy/issues/190 that Microsoft.Web behaves differently.  

Any thoughts on what is going on here?  Is this behavior expected and I've misread or misunderstood the documentation?

**Comment by trolleyboy** [comment]
P.S.  I've noticed the same behavior with the minTlsVersion Alias too... Microsoft.Web/Sites/Config/minTlsVersion.

**Comment by camillemarie** [comment]
When you say 

> HttpsOnly is set back to True

does that indicate that someone tried to set HttpsOnly to false?

Whenever a resource is updated, the policy engine will trigger deployments for all applicable DeployIfNotExists policies. So if someone tries to change HttpsOnly to false, your policy will "auto-remediate" the resource so to speak. "Existing resources" refers to resources which have not been _updated_ since the policy was put in place. It does not matter when the resource was created.

**Comment by rchithracse** [comment]
Hi All, I have tried this policy "Depolyifnotexits" for httpsonly enable .
Policy behaves as 
1. Remediation works well.
2. When I update some property on the existing resource where httpsonly is disabled . After some time, due to deployifnotexits policy in place which automatically changes the "httpsonly" property to True .  So this test case is working well.
3. When the policy is in effect, when creating new resource there is no provision to turn on or off "httpsOnly" property .  So the new resource is created with httpsOnly property is disabled . 
But my understanding , the policy should enable the this httpOnly  property . But this is not happening . Even the resources are not falling under compliance and ofcourse it is not coming under remediation tasks too . Auto remedy on new resources is not happening through policy. 

Could you please check  on this auto remedy functionality on the new resources created using "Deployifnotexits" on httpsOnly feature turnon ?

**Comment by Himalayk** [comment]
We facing the same issue.

**Comment by rahulkhengare** [comment]
> Hi All, I have tried this policy "Depolyifnotexits" for httpsonly enable .
> Policy behaves as
> 
> 1. Remediation works well.
> 2. When I update some property on the existing resource where httpsonly is disabled . After some time, due to deployifnotexits policy in place which automatically changes the "httpsonly" property to True .  So this test case is working well.
> 3. When the policy is in effect, when creating new resource there is no provision to turn on or off "httpsOnly" property .  So the new resource is created with httpsOnly property is disabled .
>    But my understanding , the policy should enable the this httpOnly  property . But this is not happening . Even the resources are not falling under compliance and ofcourse it is not coming under remediation tasks too . Auto remedy on new resources is not happening through policy.
> 
> Could you please check on this auto remedy functionality on the new resources created using "Deployifnotexits" on httpsOnly feature turnon ?

I have faced the same problem for setting up https on the web app for new resources.
Any help is appreciated.
