### ISSUE TITLE
Alias request: Microsoft.Storage/storageAccounts/blobServices/containers.publicAccess

### ISSUE THREAD

**Issue by AlexBevan** [Azure/azure-policy#260]
**Scenario**

CIS Benchmark 3.7 Ensure that 'Public access level' is set to Private for blob containers (Scored)

**Definition**

    {
    "if": {
        "allOf": [
        {
            "field": "type",
            "equals": "Microsoft.Storage/storageAccounts/blobServices/containers"
        },
        {
            "not": {
            "field": "Microsoft.Storage/storageAccounts/blobServices/containers.publicAccess",
            "equals": "None"
        }
        }
        ]
    },
    "then": {
        "effect": "deny"
    }
    }

**Comment by AlexBevan** [comment]
FYI, can see the property here: https://docs.microsoft.com/en-us/azure/templates/microsoft.storage/2018-07-01/storageaccounts/blobservices/containers

**Comment by abhijay5** [comment]
@AlexBevan i have tried the same but i am getting error that alias doesn't available. have you tested this with creation of policy definition ? 
readyState: 4
responseText: {"error":{"code":"InvalidPolicyAlias","message":"The policy definition 'd4f9a7e2-827c-4db7-8b53-f1dd8c48e16a' rule is invalid. The 'field' property 'Microsoft.Storage/storageAccounts/blobServices/containers.publicAccess' of the policy rule doesn't exist as an alias under provider 'Microsoft.Storage' and resource type 'storageAccounts/blobServices'. The supported aliases are ''. Please see https://github.com/Azure/azure-policy/blob/master/1-contribution-guide/request-alias.md to request new aliases."}}
status: 400
statusText: Bad Request

**Comment by AlexBevan** [comment]
I know it doesn't exist, I'm requesting it. See topic

**Comment by Obiwan72** [comment]
Any news when this issue is going to be fixed? We also would like to be able to use this policy.

**Comment by Ashwin1991** [comment]
This is an industry benchmark - requesting policy alias name to be made available +1

**Comment by mentat9** [comment]
Full set of aliases for Microsoft.Storage (including this one) are now published. Please try give it a try (and thank-you for waiting).

**Comment by sprilutsky01** [comment]
We tried above policy definition, but it does not like that alias. Can someone provide the appropriate alis for this Policy, please?

**Comment by mentat9** [comment]
The policy at the start of this issue uses the old incorrect alias, which has been deleted and replaced by the new correct one.

Old incorrect: ```Microsoft.Storage/storageAccounts/blobServices/containers.publicAccess```
New correct: ```Microsoft.Storage/storageAccounts/blobServices/containers/publicAccess```

@sprilutsky01, please check that you are using the correct one.

**Comment by sprilutsky01** [comment]
that works  Thank you

________________________________

**Comment by sprilutsky01** [comment]
Hi Chris,

Quick question, if you do not mind: After I list all available aliases for particular Provider/Service, where can I find the description of what it does and rationale behind that.

I am pretty new to Azure Policy and it's hard to get into the "groove", if you know what I mean.

Regards,
    Sergey Prilutsky

________________________________

**Comment by mentat9** [comment]
Yes, I do know what you mean. There isn't separate policy documentation for aliases, since they refer to the thousands of existing fields that are published by the various resource providers. Generally you need to come at it from two directions: general documentation about how policy works and specific information about a given field/alias.

This is a good place to start for general policy documentation: https://docs.microsoft.com/en-us/azure/governance/policy/.

It isn't always easy to find documentation for specific fields/aliases, but it's mostly the same problem as finding documentation for anything in Azure. Usually a web search of keywords in the alias name gets you to what's available. Including the word REST often helps focus results away from stuff that's specific to Powershell, CLI or SDKs. For example, the first hit from a search using Microsoft.Storage blobservices containers publicaccess REST is this page: https://docs.microsoft.com/en-us/rest/api/storagerp/blobcontainers/create, which is the correct documentation for this alias/field.

**Comment by sprilutsky01** [comment]
Thank you very much Chis, greatly appreciate your quick, swift response.

Regards,
   Sergey Prilutsky

________________________________

**Comment by chirurico** [comment]
> The policy at the start of this issue uses the old incorrect alias, which has been deleted and replaced by the new correct one.
> Old incorrect: Microsoft.Storage/storageAccounts/blobServices/containers.publicAccess
> New correct: Microsoft.Storage/storageAccounts/blobServices/containers/publicAccess
> @sprilutsky01, please check that you are using the correct one.

I'm sorry, but I'm afraid that this is not working yet. Can you confirm again?
I've checked the alias and there is no entrance for the old one or the new one. Try to use my example:

```
{
  "mode": "All",
  "policyRule": {
    "if": {
      "allOf": [
        {
          "field": "type",
        "equals": "Microsoft.Storage/storageAccounts/blobServices/containers"
        },
        {
          "not": {
            "field": "tags.cia",
            "matchInsensitively": "B??"
          }
        },
        {
          "not": {
            "field": "Microsoft.Storage/storageAccounts/blobServices/containers/publicAccess",
        "equals": "None"
          }
        }
      ]
    },
    "then": {
      "effect": "deny"
    }
  },
  "parameters": {}
}
```

**Comment by mentat9** [comment]
Sorry this issue was closed and didn't get updated later. The storage team decided they couldn't support per-container policy-based management on the control plane. Please see https://github.com/Azure/azure-policy/issues/131 and [**Known Issues**](https://github.com/Azure/azure-policy/blob/master/README.md#known-issues) in the [readme](https://github.com/Azure/azure-policy/blob/master/README.md) for more details.
