### ISSUE TITLE
Alias request: Microsoft.Compute/virtualMachines/extensions/settings/fileUris[*].value

### ISSUE THREAD

**Issue by remyaraya** [Azure/azure-policy#331]
### Scenario

I would like the policy to deny CreateOrUpdate VM if the specified Microsoft.Compute/virtualMachines/extensions/settings/fileUris[*].value is not provided.

### Alias

- What resource provider and resource type is involved?
  * **Resource Provider**: Microsoft.Compute/virtualMachine/extensions
  * **Type**: CustomScriptExtension
- What property on that resource type do you wish to expose?
  * settings/fileUris[*].value
### Example policy definition

```json
{
  "if": {
    "allOf": [
      {
        "field": "type",
        "equals": "Microsoft.Compute/virtualMachines"
      }
    ]
  },
  "then": {
    "effect": "deny",
    "details": {
      "type": "Microsoft.Compute/virtualMachines/extensions",
      "existenceCondition": {
        "allOf": [
          {
            "field": "Microsoft.Compute/virtualMachines/extensions/settings/fileUris[*].value",
            "equals": "https://my-sample.blob.core.windows.net/sample-cfg.ps1"
          },
          {
            "field": "Microsoft.Compute/virtualMachines/extensions/type",
            "equals": "CustomScriptExtension"
          }
        ]
      }
    }
  }
}
```

**Comment by mentat9** [comment]
Sorry, but this isn't a field that can be directly managed by the policy engine, since there is no schema published for what is found inside the settings. For example, the ```fileUris``` array field is not found anywhere in the OpenApi specs for Azure. There is already an alias published for the settings itself though (```Microsoft.Compute/virtualMachines/extensions/settings```). Maybe you can write a policy that checks the value of settings for the conditions you need to validate.
