### ISSUE TITLE
Alias request: Microsoft.Compute/disks/name

### ISSUE THREAD

**Issue by sdcscripts** [Azure/azure-policy#332]
Scenario
Use Azure Policy to check/enforce name or to exclude check for disks that are part of ASR replication or other service. 
Definition
{
"policyRule": {
"if": {
"allOf": [
{
"field": "type",
"equals": "Microsoft.Compute/disks/name"
},
{
"not": {
"field": "Microsoft.Computer/disks/name",
"like": "asrreplica"
}
}
]
},
"then": {
"effect": "Audit"
}
}
}
}

**Comment by mentat9** [comment]
We don't actually make aliases for the top level properties of the resource (e.g. name, id, type), since you can access them like this:

```
{
  "if": {
    "not": {
      "field": "name",
      "like": "asreplica"
    }
  },
  "then": {
    "effect": "audit"
  }
}
```

**Comment by sdcscripts** [comment]
Hi 

Sorry, I wasn't clear what I mean is that the name property does not appear to be available for the 'Microsoft.Compute/disks' namespace? 

Get-AzPolicyAlias -ResourceTypeMatch "disks" | select -ExpandProperty Aliases   

This shows no name field I can use for disks? 

Thanks
Shaun

**Comment by mentat9** [comment]
Correct: that's actually expected. There are 3 fields that every resource has (name, type, id). We don't create aliases for those, since they are the same for every resource (and api-version). This means you can't use alias syntax for those (and they won't be reported as aliases by Get-AzPolicyAlias). However, you can still access them directly in a policy without an alias. You just need to use a different pattern like the sample I provided above.

**Comment by sdcscripts** [comment]
Ah I understand now, thank you for clarifying that for me Chris 

Shaun
