### ISSUE TITLE
 Alias request: Microsoft.Web/hostingEnvironments.clusterSettings for DisableTls1.0 and FrontEndSSLCipherSuiteOrder

### ISSUE THREAD

**Issue by uday31in** [Azure/azure-policy#34]
**Scenario**

Disable TLS 1.0 & FrontEndSSLCipherSuiteOrder on App Service Environment.

customers who are dealing with PCI compliance audits, is how to explicitly disable TLS 1.0 for their apps.

This policy will provide required governance assurance to deny ASE createion with TLS 1.0 enabled

**Definition**

I am not sure how properties settings will surface in policy definition as this is KV pair under properties. 

```
"resources": [
{
   "apiVersion": "2015-08-01",
   "type": "Microsoft.Web/hostingEnvironments",
   "name": ...,
   "location": ...,
   "properties": {
      "clusterSettings": [
         {
                         "name": "DisableTls1.0",
                         "value": "1"

         }
      ],
      "workerPools": [ ...],
      etc...
   }
}


'''

**Comment by pilor** [comment]
The following aliases are now available:
Microsoft.Web/hostingEnvironments/clusterSettings[*].name
Microsoft.Web/hostingEnvironments/clusterSettings[*].value

Since these are just key-value pairs one way to check enablement in policy would be (untested, please test before using):
{
   "if": {
      "allOf": [
         {
            "field": "type",
            "equals": "Microsoft.Web/hostingEnvironments"
         },
         {
            "field": "Microsoft.Web/hostingEnvironments/clusterSettings[*].name",
            "notEquals": "DisableTls1.0"
         },
         {
            "field": "Microsoft.Web/hostingEnvironments/clusterSettings[*].value",
            "notEquals": "1"
         }
      ]
   },
   "then": {
      "effect": "deny"
   }
}

**Comment by nilanjandas79** [comment]
Hi Pilor,

Will the above Policy check for 1:1 name value pair ? Also after applying this policy, I am not able to create an ASE with ARM also

**Comment by pilor** [comment]
@nilanjandas79, I don't understand the question.  The policy provided above will block the creation or update of hostingEnvironments unless DisableTls1.0 = 1

**Comment by nilanjandas79** [comment]
@pilor , Two issues

1. Upon testing even if I set the clustersettings in my ARM, it is not allowing me to provision ASE
2. How does it understand from above policy that name="DisableTls1.0" has value="1"?

**Comment by pilor** [comment]
How exactly are you provisioning the ASE?  A template?  Can you provide an example (with any secrets removed)?

The policy above will not explicitly check that DisableTls1.0=1 but will check that clusterSettings has a Name=disableTls1.0 and a value=1.  Scoping multiple array conditions to the same element in the parent array isn't supported yet unfortunately.  This is probably good enough for the scenario due to the [limited number of settings allowed in clusterSettings](https://docs.microsoft.com/en-us/azure/app-service/environment/app-service-app-service-environment-custom-settings).

**Comment by nilanjandas79** [comment]
@pilor , We are using the following ARM

"resources": [
      {
          "apiVersion": "2016-09-01",
          "type": "Microsoft.Web/hostingEnvironments",
          "name":"[parameters('aseName')]",//lower case
          "kind": "ASEV2",
          "location": "[parameters('location')]",
          "properties": {
            "name": "[parameters('aseName')]",//lower case
            "location": "[parameters('location')]",
            "dnsSuffix": "[parameters('dnssuffix')]",
            "internalLoadBalancingMode": 3,
            "virtualNetwork": {
              "Id": "[parameters('VnetId')]",
              "Subnet": "[parameters('subnetName')]"
            },
            "parameters": {
                "tagging": { "value": "[variables('tagging')]" },
                "dnsSuffix": "[parameters('dnssuffix')]"
            },
            "clusterSettings": [         
          {
            "name": "DisableTls1.0",
            "value": "1"
          }
        ]
            
        },
        "dependsOn": []
    }
]

**Comment by nilanjandas79** [comment]
Hi @pilor , did you get a chance to look into it?

**Comment by pilor** [comment]
Hi, sorry for the delay.  Are you sure the failure in provisioning ASE is due to policy?  I believe your template is missing the [workerPools required property](https://docs.microsoft.com/en-us/rest/api/appservice/appserviceenvironments/createorupdate).

There is a small change I made to the policy to make it work correctly in my testing.  However, with this change it successfully denied ASE creation if I did not set DisableTls1.0=1 and only allowed the creation if it was set correctly.

```
"if": {
         "allOf": [
            {
               "field": "type",
               "equals": "Microsoft.Web/hostingEnvironments"
            },
            {
               "anyOf": [
                  {
                     "field": "Microsoft.Web/hostingEnvironments/clusterSettings[*].name",
                     "notEquals": "DisableTls1.0"
                  },
                  {
                     "field": "Microsoft.Web/hostingEnvironments/clusterSettings[*].value",
                     "notEquals": "1"
                  }
               ]
            }
         ]
      }
```

**Comment by nilano365** [comment]
@pilor , yes it is working now. The ARM is also fine that we are using. Thank you!
