### ISSUE TITLE
Issue: Alias: "Microsoft.ApiManagement/service/vpnType": not reflecting accurately "properties.vpnType" value.

### ISSUE THREAD

**Issue by mylameaccount** [Azure/azure-policy#362]
ISSUE DESCRIPTION:
The Azure Policy Alias : "Microsoft.ApiManagement/service/vpnType" seems to reflect the "properties.vpnType" value as being null instead of None, Internal, or External.
I am not sure if this should be showing "properties.vpnType" or the “properties.virtualNetworkType”. They appear to be the same value but named differently depending on if you use the Get-AzApiManagement or Get-AzResource commandlets in powershell.

If this can be corrected it would be helpful to my current efforts.

Please see the screen shots attached to this thread for detailed information on the resource and issue.
![VpnType01](https://user-images.githubusercontent.com/20546043/56401104-e8737d80-621c-11e9-8a48-58c6dd59b4cd.jpg)

**Comment by mentat9** [comment]
There were a couple of things giving you those results. First: the Microsoft.ApiManagement aliases were not fully updated. This has been corrected on our side. Second: the vpnType field is from older api versions (specifically 2016-07-07, 2016-10-10 and 2017-03-01 and it was an integer value, translated to an enum by Powershell). Api versions since then return the enum you are looking for, but on the virtualNetworkType field, which we now have provided an alias for. Please try the new alias: this should be what you are looking for.

**Comment by mentat9** [comment]
Let us know if this addresses the issue. https://github.com/Azure/azure-policy/issues/363 provides some related information.

**Comment by mylameaccount** [comment]
The "virtualNetworkType" alias covers my needs. You can close this ticket. Thank you for looking into this and clarifying.
