### ISSUE TITLE
ServiceBus alises missing?

### ISSUE THREAD

**Issue by CtrlDot** [Azure/azure-policy#365]
In the default policy set, there are 2 policies tied to ServiceBus. One that looks for diagnostic logs and the other that looks for the authorization rules.

However, when i run the following "get-azpolicyalias -namespacematch 'bus'" I don't see any servicebus aliases.

Is this policy working? Is the alias list incorrect?

Thanks

**Comment by mentat9** [comment]
The aliases for Microsoft.ServiceBus were just added this morning. However, I see they are not showing up in the output of Get-AzPolicyAlias. The problem is that the list is incorrect. This should not affect policies: the aliases are definitely there. We already have an work item open to investigate aliases missing from the output of Get-AzPolicyAlias.

**Comment by CtrlDot** [comment]
Thanks @mentat9 
Is there a more authoritative list of aliases I can be looking at?

**Comment by mentat9** [comment]
Sorry, no. The list returned by Get-AzPolicyAlias is the list returned by the REST layer. There is no other way to query.
