### ISSUE TITLE
Unclear how to confirm completed policy evaluation for testing

### ISSUE THREAD

**Issue by rwsanders** [Azure/azure-policy#408]
This question originates from the larger problem of testing policy definitions.  Currently we are building a testing framework for policies and we are using the ["on-demand evaluation" procedure documented by Microsoft](https://docs.microsoft.com/en-us/azure/governance/policy/how-to/get-compliance-data#on-demand-evaluation-scan). 

Our tests deploy the policy definitions and then assign them via ARM template deployment API.  Then we trigger an on-demand policy evaluation and wait for the link returned by the Location header to return a 200.  At that point we check the policy results and determine pass or fail for our test.  

We have noticed that this works about 95% of the time.  Sometimes we receive false negatives, where we have a good policy but the on-demand trigger and completion feedback has still not fully evaluated the new policy.  My question is if there is any race condition in the process I have described (deployment, assignment, trigger, completion feedback) where we should further wait to make sure the policy is completely evaluated before determining the results of our test?

**Comment by cemheren** [comment]
This is possible in some cases where the on-demand trigger hits an evaluation instance where the old policies are cached/not replicated yet. Unfortunately due to the distributed nature of the system and evaluation related performance requirements accuracy is only guaranteed after 30 mins of the assignment. Otherwise it's best effort (although you are more likely to get the right result than not). 

There are plans to improve policy definition authoring experience and we are open to feedback.

**Comment by rwsanders** [comment]
"accuracy is only guaranteed after 30 mins of the assignment", if we modify the policy definition without touching the existing assignment, would this 30 minute time period still apply?

**Comment by cemheren** [comment]
Yes it does, internally we merge the policy definition and the assignment to create an actionable policy. Otherwise we can't make sense of the parameters.

**Comment by rwsanders** [comment]
I expected that answer but just wanted to be sure.  Thank you.
