### ISSUE TITLE
Alias request: "Microsoft.Insights/diagnosticSettings/name

### ISSUE THREAD

**Issue by ruthlees** [Azure/azure-policy#424]
What are you trying to achieve using Azure Policy?

Hi, trying to use azure policy to append diagnostic settings on resources, such as Key Vaults, when they are being newly created. This will ensure that the diagnostic setting we went to go to Sentinel are automatically added when it is created. 

What I would like to do is to be able to use this alias on all the resources that use diagnostic settings so that I can name the feed.

  "policyRule": {
          "if": {
            "field": "type",
            "equals": "Microsoft.KeyVault/vaults"
            },
          "then": {
             "effect": "append",
             "details": [
                        {
                            "field": "Microsoft.Insights/diagnosticSettings/name",
                            "value": "[parameters('diagnosticName')]"
                        },
                        {
                            "field": "Microsoft.Insights/diagnosticSettings/logs.enabled",
                            "value": "[parameters('logsEnabled')]"
                        },
                        {
                            "field": "Microsoft.Insights/diagnosticSettings/metrics.enabled",
                            "value": "[parameters('metricsEnabled')]"
                        },
                        {
                            "field": "Microsoft.Insights/diagnosticSettings/workspaceId",
                            "value": "[parameters('logAnalytics')]"
                        }
                    ]
                }   
            }

**Comment by mentat9** [comment]
Name is a top-level property on the Microsoft.Insights/diagnosticSettings resource type, so an alias isn't needed. We don't generate aliases for top-level properties, since they are directly accessible in the policy language.

Note the above policy won't work, since policies only apply to a single resource type (Microsoft.KeyVaults/vaults in this case). I'm not sure how to write a policy that does what you want, but it might be worth experimenting with a deployIfNotExists policy and see if that helps.
