### ISSUE TITLE
Alias Request: Microsoft.Web/sites/config/siteextensions

### ISSUE THREAD

**Issue by VOVELEE** [Azure/azure-policy#454]
Scenario:
Limit WebApps to use site extensions which are approved on company level

Definition:

{
    "if": {
        "allOf": [
            {
                "field": "type",
                "equals": "Microsoft.Web/sites/config"
            },
            {
                "field": "Microsoft.Web/sites/config/siteextensions.name",
                "notIn": "[parameters('listOfAllowedExtensions')]"
            }
        ]
    },
    "then": {
        "effect": "Deny"
    }
}

Expose Microsoft.Web/sites/config/siteextensions

**Comment by mentat9** [comment]
Closing this issue per changes to the support model for this repo. See the [**Getting Support**](https://github.com/Azure/azure-policy#getting-support) section in the [readme](https://github.com/Azure/azure-policy/blob/master/README.md) for details and Azure Policy support information.

Note these particular properties are explicitly exempt from policy management due to the way they are implemented by the Microsoft.Web resource provider and cannot be managed through ARM. If policy-based governance of these properties is an important scenario for you, please open a support ticket against the Web team to get help.
