### ISSUE TITLE
Alias request: Microsoft.Compute/virtualMachines/instanceView.disks[*].encryptionSettings

### ISSUE THREAD

**Issue by punit1396** [Azure/azure-policy#500]
# Scenario
The ADE one pass related encryption information resides at the disk level. A user can see this through the instance view of the VM.
There already exists an alias that helps check if the encryptionSettings are enabled
_Microsoft.Compute/virtualMachines/instanceView.disks[*].encryptionSettings[*].enabled_
But in case of unencrypted VMs/disks, encryptionSettings do not exist. Thus, the above alias doesn't help.
Hence, the ask for a new alias that helps check for the existence of the encryption settings in the instance view.
# Alias
Include details about the alias being requested. Details on aliases are available here.
What resource provider and resource type is involved?
_Microsoft.Compute/virtualMachines_
What property on that resource type do you wish to expose?
_EncryptionSettingsCollection_
A similar alias exists for OS disks:
_Microsoft.Compute/virtualMachines/storageProfile.osDisk.encryptionSettings_
# Example policy definition
Please include a sample policy definition that shows how you would like to use this new alias.
{
"if": {
"allOf": [
{
"field": "type",
"equals": "Microsoft.Compute/virtualMachines"
},
{
"field": "Microsoft.Compute/virtualMachines/instanceView.disks[*].encryptionSettings",
"exists": "false"
}
]
}
]
},
"then": {
"effect": "audit"
}
}

**Comment by punit1396** [comment]
Also, does a collection based exists check return true if even one exists or only if all exists?

**Comment by mentat9** [comment]
Closing this issue per the support model for this repo. See the [**Getting Support**](https://github.com/Azure/azure-policy#getting-support) section in the [readme](https://github.com/Azure/azure-policy/blob/master/README.md) for details and Azure Policy support information.

Note: properties of Microsoft.Compute/virtualMachines/instanceView are identified in the [Known Issues](https://github.com/Azure/azure-policy/blob/master/README.md#known-issues) section of the readme. These properties do not support Azure Policy, so aliases for them are not generated, although there are a handful of legacy aliases that cannot be removed due to the fact they are in use by existing policies.
