### ISSUE TITLE
Azure VM repair blocked by policy (AZ repair )

### ISSUE THREAD

**Issue by theBlueclouds** [Azure/azure-policy#528]
we followed [this ](https://docs.microsoft.com/en-us/azure/virtual-machines/troubleshooting/repair-windows-vm-using-azure-virtual-machine-repair-commands) and when we reach `az vm repair create -g MyResourceGroup -n myVM --repair-username username --repair-password password!234 --verbose` we get policy violation error. 
Regardless of which policy it is , is there a way to prevent this from happening by temporily switching off policies? 

The policy that cause it to fail was titled : Ensure Subnets have CPS NSG V2. Policydefinition effect: Append,
Not sure why subnet policy is affecting a machine repair.

**Comment by kenieva** [comment]
Hi, there are two ways which you can bypass the policy validation. 1) You can exclude the resource from the policy (https://docs.microsoft.com/en-us/azure/governance/policy/concepts/assignment-structure#excluded-scopes). 2) You can turn mode off so that the policy is not enforced. Be aware that after deployment, you should turn it back on! (https://docs.microsoft.com/en-us/azure/governance/policy/concepts/assignment-structure#enforcement-mode).
