### ISSUE TITLE
Incorrect policy example

### ISSUE THREAD

**Issue by pt-arvind** [Azure/azure-policy#539]
https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Compute/VMSkusAllowed_Deny.json

this leads me to believe that the policy is for denying OS images but it's actually for denying size limitations. Denying OSes is as follows:

https://github.com/Azure/Community-Policy/blob/master/Policies/Compute/allowed-vm-os/azurepolicy.json

May want to update your documentation or clarify it better

**Comment by pilor** [comment]
@DCtheGeek both VM docs and the VM blades in the portal refer to "sku" as "size".  Should we change the strings in the built-in?

**Comment by DCtheGeek** [comment]
I agree and that makes sense to me, even though the property is `sku.name`.  Let's double check with @cynthn who owns VM docs and can definitively clarify on which use is preferred.

**Comment by cynthn** [comment]
@DCtheGeek Yep, Compute uses "SKU" for VM sizes, since that is their "product". OSs are Windows\Linux etc. Does that help?

**Comment by DCtheGeek** [comment]
@cynthn I think the question is that the portal and docs say "sizes" instead of "SKU", so we wanted to be aligned to whatever the right branding should be in the description of this policy definition.  I know the property is `SKU`, but since docs and portal descriptively call it 'sizes' (such as [here](https://docs.microsoft.com/azure/virtual-machines/windows/sizes)), should the description here be `SKU` or `sizes`?

**Comment by cynthn** [comment]
Oh, sorry. Yeah, “sizes” is clearer. We often use "size SKU", if you think that helps make it clearer.

**Comment by DCtheGeek** [comment]
That makes sense to me, thanks!

@pilor - Let's update the title/description to Cynthia's recommendation: `size SKU`. I think that's much more clear than one term or the other.

**Comment by pilor** [comment]
Change has been made.  It will go out with the next built-in policy release.

**Comment by pt-arvind** [comment]
thanks guys
