### ISSUE TITLE
Problem with Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/throughputSettings

### ISSUE THREAD

**Issue by jagratimodi** [Azure/azure-policy#552]
Hello! I need some help regarding this policy:

```
{
      "if": {
        "allOf": [
          {
            "field": "type",
            "equals": "Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/throughputSettings"
          },
          {
            "field": "Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/throughputSettings/default.resource.throughput",
            "greater": 400
          }
        ]
      },
      "then": {
        "effect": "deny"
      }
    }
```
This policy does not deny/restrict from creating of containers with more than 400 RUs.  The only effect of policy I can see is later the Compliance state changes to "Non-compliant". 
But why does the policy not restrict the creating of resource?

I think I am missing something here. Please help!

**Comment by pilor** [comment]
Throughput is not set on initial create via the throughputSettings API.  See this template for an example:  https://docs.microsoft.com/en-us/azure/cosmos-db/manage-sql-with-resource-manager#create-resource

There is not currently a policy alias for options.throughput on the container since it is not returned on future GET requests.  To request new aliases see https://github.com/Azure/azure-policy#alias-requests
