### ISSUE TITLE
CosmosDB "allowed locations" policy should normalise location names consistently (i.e. "australiaeast" vs "Australia East")

### ISSUE THREAD

**Issue by pacon-vib** [Azure/azure-policy#612]
The built-in policy "Azure Cosmos DB allowed locations" compares a lower-cased, spaces-removed version of the deployed location names against the unnormalised allowed location names. This causes problems if you write location names Like This everywhere.

https://github.com/Azure/azure-policy/blob/6fcda5b67d0295bf5803445ff88e42ff9aae1ed1/built-in-policies/policyDefinitions/Cosmos%20DB/Cosmos_Locations_Deny.json#L45-L46

Policy ID is: `/providers/Microsoft.Authorization/policyDefinitions/0473574d-2d43-4217-aefe-941fcdf7e684`

What happened was that I was deploying both policy assignments and CosmosDB from Terraform, using the location "Australia East", and getting the CosmosDB blocked by policy. I then tried changing the parameter in the policy assignment to "australiaeast" and now the CosmosDB (deployed to "Australia East") works.

I don't know what the correct way to write Azure location names is but there seems to be a mix of "locationname" and "Location Name" floating around, so it would be helpful if this policy could either leave the names as-is or normalise both sets of names to the one standard.

The other "allowed locations" policies that I have seen (e.g. allowed locations for resource groups) don't do any transformations to the location names.

Thankyou for your consideration.

**Comment by pilor** [comment]
Informing the appropriate people

**Comment by shurd** [comment]
Hi @pacon-vib, how did you assign this policy? This list is a strong type, so when creating through the portal, the location names selected through the provided list should all be normalized.

When creating via the cli or other methods, I do not believe there is any validation done to the inputs so whatever string you provide will be added as the parameter. I do not believe there is currently a way when using template functions to apply a normalization to every item in the parameter array when using "in". 

We normalized the incoming location because our portal form sends the proper name (ie "East US" instead of eastus). If someone were exclusively using the portal, then assigning this policy would prevent them from creating any Cosmos DB accounts without the normalization.

**Comment by pacon-vib** [comment]
Hey @shurd. I assigned the policy with Terraform.

**Comment by shurd** [comment]
@pacon-vib thanks for the quick follow-up. I will check with some people on the policy team to see if normalizing both inputs is feasible and get back to you with any solutions we find.

**Comment by pacon-vib** [comment]
Thanks @shurd. I'm not fussy about the outcome, I just noticed that this was the only built-in policy where you have to write "australiaeast" rather than "Australia East" so I thought I should let you know. None of the other built-in policies do any normalisation at all.

**Comment by kenieva** [comment]
@shurd, is there any updates on this?

**Comment by kenieva** [comment]
There hasn't been any response on this thread so I will close the issue. If the problem persist or there are updates, please re-open.
