### ISSUE TITLE
Microsoft.Sql/servers/virtualNetworkRules/virtualNetworkSubnetId missing array support

### ISSUE THREAD

**Issue by cannehag** [Azure/azure-policy#672]
Referring to sample https://github.com/Azure/azure-policy/blob/master/samples/SQL/audit-sql-server-vnet-rule/azurepolicy.json

I have multiple Virtual Network subnets configured on our SQL-Server and there is no way to verify that all of them are present since the policy alias doesn't support arrays. It will only match on the first configured subnet.

I would expect to find a "Microsoft.Sql/servers/virtualNetworkRules[*]" alias (or however you defined them...)

This is how my virtualNetworkRules resource looks (resource names mocked):

```json
{
  "value": [
    {
      "properties": {
        "virtualNetworkSubnetId": "/subscriptions/.../resourceGroups/.../providers/Microsoft.Network/virtualNetworks/MyVnet/subnets/MySubnet1",
        "ignoreMissingVnetServiceEndpoint": false,
        "state": "Ready"
      },
      "id": "/subscriptions/.../resourceGroups/.../providers/Microsoft.Sql/servers/.../virtualNetworkRules/newVnetRule1",
      "name": "newVnetRule1",
      "type": "Microsoft.Sql/servers/virtualNetworkRules"
    },
    {
      "properties": {
        "virtualNetworkSubnetId": "/subscriptions/.../resourceGroups/.../providers/Microsoft.Network/virtualNetworks/MyVnet/subnets/MySubnet2",
        "ignoreMissingVnetServiceEndpoint": false,
        "state": "Ready"
      },
      "id": "/subscriptions/.../resourceGroups/.../providers/Microsoft.Sql/servers/.../virtualNetworkRules/newVnetRule2",
      "name": "newVnetRule2",
      "type": "Microsoft.Sql/servers/virtualNetworkRules"
    }
  ]
}
```

The only way to define this policy today is using an existenceCondition like this:
```json
  "type": "Microsoft.Sql/servers/virtualNetworkRules",
  "existenceCondition": {
    "field": "Microsoft.Sql/servers/virtualNetworkRules/virtualNetworkSubnetId",
  ...
}
```

Which will evaluate the policy according to this:
![image](https://user-images.githubusercontent.com/568378/100739577-8d81a080-33d7-11eb-9343-dad085119af5.png)

**Comment by calecarter** [comment]
The problem here is that the collection of Microsoft.Sql/servers/virtualNetworkRules you are referring to is a collection GET through Azure Resource Manager (ARM).  The collection [*] aliases are for properties in types that are collections.  That is not the case here as this (Microsoft.Sql/servers/virtualNetworkRules) is a full fledged resource type.  The intention for the policy you referenced (https://github.com/Azure/azure-policy/blob/master/samples/SQL/audit-sql-server-vnet-rule/azurepolicy.json) is to create a separate assignment for each virtualNetworkSubnetId you are expecting.  That will flag any resource that does not have the specified virtualNetworkSubnetId.  Hope this helps.
