### ISSUE TITLE
Default Policy should include Gen2 images

### ISSUE THREAD

**Issue by JustinGrote** [Azure/azure-policy#807]
None of the Gen2 images are listed here, they should be.

https://github.com/Azure/azure-policy/blob/0a73852f3ec90ff19c2774935d046d0ccc0653b2/built-in-policies/policyDefinitions/Backup/VirtualMachineWithTag_Backup_Deploy.json#L91-L111

For instance, the policy does not apply to MicrosoftWindowsServer/WindowsServer/2019-datacenter-smalldisk-g2:latest image, so all of our servers deployed were not being backed up.

**Comment by nehakulkarni123** [comment]
Hi @JustinGrote, this built-in definition has since been updated: https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Backup/VirtualMachineWithTag_Backup_Deploy.json.

If you need to add additional values, you can alternatively create a custom definition and add these values.
