### ISSUE TITLE
CIS 1.1.0 Policy Ensure that a Log Profile exists using a legacy method

### ISSUE THREAD

**Issue by gavhooper** [Azure/azure-policy#828]
According to this site using Microsoft.Insights/logprofiles is the legacy method: [Azure Activity log](https://docs.microsoft.com/en-us/azure/azure-monitor/essentials/activity-log#legacy-collection-methods)

But in CIS 1.1.0 the policy is looking that this is configured. Is there a reason for this or does it need to be updated to reflect the new way of working?

**Comment by jomolesk** [comment]
Hi @gavhooper -- The policies included in the CIS Microsoft Azure Foundations Benchmark v1.1.0 initiative are intended to align to the CIS recommendations as closely as possible. As CIS improves the benchmarks in subsequent versions, we aim to have a corresponding published initiative that aligns to those recommendations. Since v1.1.0 of the benchmark has recommendations specifically around Log Profiles, these policies are included. However, I would recommend to consider using a newer version of the benchmark (and the corresponding newer initiative). It is likely that these policies will be deprecated in the future as they are related to the legacy collection methods. (Note -- Microsoft participates in CIS' consensus process for developing the benchmark, but does not control the content of the benchmark.)

**Comment by nehakulkarni123** [comment]
I will close this item since John has provided an answer. If you have further questions, feel free to re-open or create a new issue.
