### ISSUE TITLE
isComplianceCheck field no longer reports to Activity Log

### ISSUE THREAD

**Issue by artisticcheese** [Azure/azure-policy#853]
Is "isComplianceCheck" shall be written to Azure Activity Log? Below does not return any results anymore

> AzureActivity
> | where CategoryValue == "Policy" 
> | extend isComplianceCheck_ = tostring(Properties_d.isComplianceCheck)
> | where isComplianceCheck_ == "True"

**Comment by pilor** [comment]
Not with a value of "true".  You'll still see isComplianceCheck=false entries which indicate policy evaluation actions that occurred due to a resource operation (i.e. denying an incoming request).

If you want to consume events that indicate changes in the state of resources as a result of compliance scans these are now published to event grid:  https://docs.microsoft.com/en-us/azure/governance/policy/tutorials/route-state-change-events

**Comment by artisticcheese** [comment]
This stopped working at some point in last 2 years? Because I was able to see those events before in Azure Activity Logs and had alerts tied to those

**Comment by pilor** [comment]
Yes, those messages were deprecated quite a while ago when the event grid based messages became available (I don't remember the exact date).  isComplianceCheck=false will still show you all the evaluations happening as a result of user actions if you intend to alert on that.  If you want alerts based on compliance state changes of existing resources (regardless of why the state changed) the event grid based approach is what must be used.

**Comment by slavizh** [comment]
@pilor I would strongly suggest to announce these breaking changes in advance so you can give time people to prepare and migrate. If someone had alert replying on those logs no they will not have idea that their alert no longer works.

**Comment by nehakulkarni123** [comment]
Hi @slavizh, thanks for the feedback. We typically send a few email reminds to customers prior to deprecations, and I'll investigate to see if that practice was done for this as well.
