### ISSUE TITLE
Deploy - Configure diagnostic settings for SQL Databases to Log Analytics workspace should exclude the master database

### ISSUE THREAD

**Issue by Pedroms1** [Azure/azure-policy#869]
#### Details of the scenario you tried and the problem that is occurring

This policy is returning a non compliant status on synapse master databases.
The issue is that it is not possible to enable diagnostic settings on the master database in any scenario.

#### Verbose logs showing the problem
N/A 

#### Suggested solution to the issue

Exclude the master database on this policy.

**Comment by spoelly** [comment]
I posted here a suggestion for the team. https://github.com/Azure/azure-policy/issues/872

**Comment by kenieva** [comment]
It is possible to exemption resource types such as SQL Database using exemptions resource selectors. Or by updating the policy definition.

**Comment by matthetherington** [comment]
@kenieva could this be reopened?

It's indeed possible to create an exemption, but it shouldn't be required. If Azure Policy has flagged master as uncompliant, it is not possible for anyone to correct that - so the flagging is a mistake.

**Comment by mbrouwer** [comment]
This really should be reopened because we dont want to exempt databases, we want to audit databases, just not the ones of kind "v12.0,system" only on "v12.0,user" or we should have the option to apply the settings to databases of kind "v12.0,system":
<img width="327" alt="image" src="https://github.com/Azure/azure-policy/assets/933902/c1e245fa-b39e-46f0-ba96-749d31450787">
