### ISSUE TITLE
Kubernetes cluster pod security baseline and restricted standards for Linux-based workloads default allowed capabilities

### ISSUE THREAD

**Issue by akathimi** [Azure/azure-policy#899]
The default allowed capabilities seem to be illogical, since they are allowing insecure capabilities to be used by the pods.

https://github.com/Azure/azure-policy/blob/3e8d7c293826173171066b1ed1c1b0be5d236b2f/built-in-policies/policySetDefinitions/Kubernetes/Kubernetes_PSPBaselineStandard.json#L113

https://github.com/Azure/azure-policy/blob/3e8d7c293826173171066b1ed1c1b0be5d236b2f/built-in-policies/policySetDefinitions/Kubernetes/Kubernetes_PSPRestrictedStandard.json#L128

The correct behavior should be (at least on the restricted standards) to have an empty list in order to block everything.

**Comment by nehakulkarni123** [comment]
@fseldow to please take a look.

**Comment by fseldow** [comment]
empty list will not block everything. These capabilities are by default enabled even if they are not configured in capability-add spec.
To restrict these capacities, will add parameter requiredDropCapabilities. The default value is still empty list considering it might be break change for customer already using it. But customer can set it as ["ALL"] to block everything

**Comment by fseldow** [comment]
Update Summary:
1. Add parameter `Allowed add capabilities` and `Required drop capabilities`
2. The default value of parameter remains considering that it could be break change for existed assignment
3. Only change initiative `restricted standards`. Baseline initiative does not change. 
4. ETA around 1 month for SDP release since the comment date.
